services:
  webserver:
    build: ./api
    privileged: true
    command: ['python', '-u', 'main.py']
    volumes:
      - './api/src:/usr/src/app'
    ports:
      - 5000:5000
    environment:
      MQTT_HOST: '10.5.61.199'
      MQTT_PORT: 1883
      SERVER_ID: 7
    restart: always